### ISSUE TITLE
Address should be ServiceAddress

### ISSUE THREAD

**Issue by TobyColeman** [samstefan/consul-service-wrapper#9]
Docs: https://www.consul.io/api/catalog.html#serviceaddress

 🔔  [offending line](https://github.com/samstefan/consul-service-wrapper/blob/master/lib/index.js#L178) 🔔

**Comment by samstefan** [comment]
Fixed in #10

**Comment by nicolaslt** [comment]
Not Fixed :new_moon_with_face:
